name: CMake Build and Test

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define the jobs that will run in this workflow
jobs:
  build:

    # Run the job on different operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Set the job to run on the specified operating system
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.14"

      # Step 3: Set up a compiler (only necessary for Windows)
      - name: Set up compiler
        if: matrix.os == 'windows-latest'
        uses: actions/setup-msbuild@v1
        with:
          msbuild-version: '16.0'

      # Step 4: Configure CMake
      - name: Configure with CMake
        run: cmake -S . -B build

      # Step 5: Build the project
      - name: Build with CMake
        run: cmake --build build

      # Step 6: Run tests
      - name: Run tests
        run: ctest --output-on-failure -C Debug -S build
