name: CMake Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y wget
            wget https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo sh cmake-3.29.0-linux-x86_64.sh --skip-license --prefix=/opt/cmake
            echo "/opt/cmake/bin" >> $GITHUB_PATH
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install cmake --version=3.29.0 -y
          fi

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Run tests
        run: ctest --output-on-failure --build-config Debug --test-dir build
