name: CMake Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget htt
