name: CMake Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # Run the job on Ubuntu, macOS, and Windows
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.14"

      # Step 3: Set up compiler (specific configuration for Windows if needed)
      - name: Set up compiler on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          set CC=cl
          set CXX=cl

      # Step 4: Configure CMake
      - name: Configure with CMake
        run: cmake -S . -B build

      # Step 5: Build the project
      - name: Build with CMake
        run: cmake --build build

      # Step 6: Run tests
      - name: Run tests
        run: ctest --output-on-failure -C Debug -S build
